In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
%%time
#Ataque DDoS de exploração
UDPlag = pd.read_csv('/content/drive/My Drive/UDPLag.csv', low_memory=False)
syn = pd.read_csv('/content/drive/My Drive/Syn.csv', low_memory=False)
UDP = pd.read_csv('/content/drive/My Drive/DrDoS_UDP.csv', low_memory=False)

#Ataque DDoS de refleção
LDAP = pd.read_csv('/content/drive/My Drive/DrDoS_LDAP.csv', low_memory=False)
msql = pd.read_csv('/content/drive/My Drive/DrDoS_MSSQL.csv', low_memory=False)
netbios = pd.read_csv('/content/drive/My Drive/DrDoS_NetBIOS.csv', low_memory=False)

CPU times: user 4min 9s, sys: 30.6 s, total: 4min 39s
Wall time: 5min 52s

In [ ]:
syn.head()

   Unnamed: 0                                Flow ID  ...  Inbound   Label
0      281052  172.16.0.5-192.168.50.1-53058-53058-6  ...        1     Syn
1      450424  172.16.0.5-192.168.50.1-32237-32237-6  ...        1     Syn
2      182979   172.16.0.5-192.168.50.1-60495-9840-6  ...        1     Syn
3       41540  172.16.0.5-192.168.50.1-59724-59724-6  ...        1     Syn
4      358711  172.16.0.5-192.168.50.1-60496-32538-6  ...        1     Syn

[5 rows x 88 columns]

In [ ]:
print('Ataque de exploração UDPLag:', UDPlag.groupby(by=' Label').size(), 
      '\n\nAtaque de exploração Syn:', syn.groupby(by=' Label').size(),
      '\n\nAtaque de exploração UDP:', UDP.groupby(by=' Label').size(),
      '\n\nAtaque de exploração LDAP:', LDAP.groupby(by=' Label').size(),
      '\n\nAtaque de exploração MSSQL:', msql.groupby(by=' Label').size(),
      '\n\nAtaque de exploração NetBIOS:', netbios.groupby(by=' Label').size())

Ataque de exploração UDPLag:  Label
BENIGN       3705
UDP-lag    366461
WebDDoS       439
dtype: int64

Ataque de exploração Syn:  Label
BENIGN        392
Syn       1582289
dtype: int64

Ataque de exploração UDP:  Label
BENIGN          2157
DrDoS_UDP    3134645
dtype: int64

Ataque de exploração LDAP:  Label
BENIGN           1612
DrDoS_LDAP    2179930
dtype: int64

Ataque de exploração MSSQL:  Label
BENIGN            2006
DrDoS_MSSQL    4522492
dtype: int64

Ataque de exploração NetBIOS:  Label
BENIGN              1707
DrDoS_NetBIOS    4093279
dtype: int64

## Conversão "Label" em numeral

In [ ]:
# Conversão "Label" em numeral
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
UDPlag[' Label'] = labelencoder.fit_transform(UDPlag[' Label'])
syn[' Label'] = labelencoder.fit_transform(syn[' Label'])
UDP[' Label'] = labelencoder.fit_transform(UDP[' Label'])
LDAP[' Label'] = labelencoder.fit_transform(LDAP[' Label'])
msql[' Label'] = labelencoder.fit_transform(msql[' Label'])
netbios[' Label'] = labelencoder.fit_transform(netbios[' Label'])

print('Ataque de exploração UDPLag:', UDPlag.groupby(by=' Label').size(), 
      '\n\nAtaque de exploração Syn:', syn.groupby(by=' Label').size(),
      '\n\nAtaque de exploração UDP:', UDP.groupby(by=' Label').size(),
      '\n\nAtaque de exploração LDAP:', LDAP.groupby(by=' Label').size(),
      '\n\nAtaque de exploração MSSQL:', msql.groupby(by=' Label').size(),
      '\n\nAtaque de exploração NetBIOS:', netbios.groupby(by=' Label').size())

Ataque de exploração UDPLag:  Label
0      3705
1    366461
2       439
dtype: int64

Ataque de exploração Syn:  Label
0        392
1    1582289
dtype: int64

Ataque de exploração UDP:  Label
0       2157
1    3134645
dtype: int64

Ataque de exploração LDAP:  Label
0       1612
1    2179930
dtype: int64

Ataque de exploração MSSQL:  Label
0       2006
1    4522492
dtype: int64

Ataque de exploração NetBIOS:  Label
0       1707
1    4093279
dtype: int64

In [ ]:
msql.columns

Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')

## Remoção das Informações do soquete

In [ ]:
# Remoção das Informações do soquete
UDPlag.drop(['Unnamed: 0' ,'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)
syn.drop(['Unnamed: 0' ,'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)
UDP.drop(['Unnamed: 0' ,'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)
LDAP.drop(['Unnamed: 0' ,'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)
msql.drop(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)
netbios.drop(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', 'SimillarHTTP', ' Inbound'], axis=1, inplace=True)

In [ ]:
UDPlag.head()

    Flow Duration   Total Fwd Packets  ...   Idle Min   Label
0               1                   2  ...        0.0       1
1               1                   2  ...        0.0       1
2               2                   2  ...        0.0       1
3               2                   2  ...        0.0       1
4               1                   2  ...        0.0       1

[5 rows x 78 columns]

In [ ]:
#Remoção dos espaços em branco
def correct_space(space):
    space = space.replace(' ', '')
    return space

In [ ]:
UDPlag = UDPlag.apply(correct_space)
syn = syn.apply(correct_space)
UDP = UDP.apply(correct_space)
LDAP = LDAP.apply(correct_space)
msql = msql.apply(correct_space)
netbios = netbios.apply(correct_space)

## Remoção dos valores infinite e valores NaN

In [ ]:
UDPlag.replace([np.inf, -np.inf], np.nan, inplace=True)
syn.replace([np.inf, -np.inf], np.nan, inplace=True)
UDP.replace([np.inf, -np.inf], np.nan, inplace=True)
LDAP.replace([np.inf, -np.inf], np.nan, inplace=True)
msql.replace([np.inf, -np.inf], np.nan, inplace=True)
netbios.replace([np.inf, -np.inf], np.nan, inplace=True)

In [ ]:
UDPlag = UDPlag.dropna()
syn = syn.dropna()
UDP = UDP.dropna()
LDAP = LDAP.dropna()
msql = msql.dropna()
netbios = netbios.dropna()